/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as ApiCommandsStartRouteImport } from './routes/api/commands/start'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCommandsStreamSessionIdRouteImport } from './routes/api/commands/stream.$sessionId'
import { Route as ApiCommandsStdinSessionIdRouteImport } from './routes/api/commands/stdin.$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiCommandsStartRoute = ApiCommandsStartRouteImport.update({
  id: '/api/commands/start',
  path: '/api/commands/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommandsStreamSessionIdRoute =
  ApiCommandsStreamSessionIdRouteImport.update({
    id: '/api/commands/stream/$sessionId',
    path: '/api/commands/stream/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommandsStdinSessionIdRoute =
  ApiCommandsStdinSessionIdRouteImport.update({
    id: '/api/commands/stdin/$sessionId',
    path: '/api/commands/stdin/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof DashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/commands/start': typeof ApiCommandsStartRoute
  '/api/commands/stdin/$sessionId': typeof ApiCommandsStdinSessionIdRoute
  '/api/commands/stream/$sessionId': typeof ApiCommandsStreamSessionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof DashboardSettingsRoute
  '/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/commands/start': typeof ApiCommandsStartRoute
  '/api/commands/stdin/$sessionId': typeof ApiCommandsStdinSessionIdRoute
  '/api/commands/stream/$sessionId': typeof ApiCommandsStreamSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/commands/start': typeof ApiCommandsStartRoute
  '/api/commands/stdin/$sessionId': typeof ApiCommandsStdinSessionIdRoute
  '/api/commands/stream/$sessionId': typeof ApiCommandsStreamSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/api/auth/$'
    | '/api/commands/start'
    | '/api/commands/stdin/$sessionId'
    | '/api/commands/stream/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/'
    | '/api/auth/$'
    | '/api/commands/start'
    | '/api/commands/stdin/$sessionId'
    | '/api/commands/stream/$sessionId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/settings'
    | '/_dashboard/'
    | '/api/auth/$'
    | '/api/commands/start'
    | '/api/commands/stdin/$sessionId'
    | '/api/commands/stream/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCommandsStartRoute: typeof ApiCommandsStartRoute
  ApiCommandsStdinSessionIdRoute: typeof ApiCommandsStdinSessionIdRoute
  ApiCommandsStreamSessionIdRoute: typeof ApiCommandsStreamSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/commands/start': {
      id: '/api/commands/start'
      path: '/api/commands/start'
      fullPath: '/api/commands/start'
      preLoaderRoute: typeof ApiCommandsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commands/stream/$sessionId': {
      id: '/api/commands/stream/$sessionId'
      path: '/api/commands/stream/$sessionId'
      fullPath: '/api/commands/stream/$sessionId'
      preLoaderRoute: typeof ApiCommandsStreamSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commands/stdin/$sessionId': {
      id: '/api/commands/stdin/$sessionId'
      path: '/api/commands/stdin/$sessionId'
      fullPath: '/api/commands/stdin/$sessionId'
      preLoaderRoute: typeof ApiCommandsStdinSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCommandsStartRoute: ApiCommandsStartRoute,
  ApiCommandsStdinSessionIdRoute: ApiCommandsStdinSessionIdRoute,
  ApiCommandsStreamSessionIdRoute: ApiCommandsStreamSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
